class: Nightblade Bow
name: 'Notepad'
evade: 'shift'
swap: 'q'
skill01: '1'
skill02: '2'
skill03: '3'
skill04: '4'
skill05: '5'
skill06: '1'
skill07: '2'
skill08: '3'
skill09: '4'
skill10: '5'
skillUlt: 'r'
